# pytorch 教程
## 1、pytorch 基础
这里就不再介绍 pytorch 的安装了，开始我们的教程的第一部分，介绍 pytorch 处理的对象以及操作。

### 1.1、Tensor
pytorch 里面最基本的操作对象，tensor

In [1]:
import torch

In [2]:
import numpy as np

In [5]:
# 返回的数组大小 5x4 的矩阵
torch.Tensor(5,4)

tensor([[ 1.9618e-43,  1.5554e-43,  1.5975e-43,  1.3873e-43],
        [ 1.4574e-43,  6.4460e-44,  1.1771e-43,  1.4153e-43],
        [ 1.5414e-43,  1.6115e-43,  1.5554e-43,  1.5975e-43],
        [ 5.6052e-44,  7.4269e-44,  6.1657e-44,  7.2868e-44],
        [ 5.7453e-44,  7.3313e+22,  1.8471e+25,  4.1216e+21]])

In [7]:
# 返回的数组大小是 5x4 的矩阵，初始化是 0~1 的均匀分布
torch.rand(5,4)

tensor([[ 0.7319,  0.9140,  0.7606,  0.7159],
        [ 0.2685,  0.6484,  0.7076,  0.4852],
        [ 0.0037,  0.0202,  0.0826,  0.2507],
        [ 0.4765,  0.9968,  0.0194,  0.8681],
        [ 0.2938,  0.5170,  0.6764,  0.0367]])

In [9]:
# 得到矩阵大小
a = torch.rand(5,4)
a.size()

torch.Size([5, 4])

In [11]:
# numpy 类似的返回 5x4 大小的矩阵
np.ones((5,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [13]:
# numpy 和 torc.Tensor 之间的转换
a = torch.rand(5,4)
b = a.numpy()
print(b)

[[ 0.6287986   0.90508151  0.11585796  0.25815994]
 [ 0.7688539   0.05344862  0.67173809  0.38229114]
 [ 0.94842637  0.77569878  0.95060408  0.36145872]
 [ 0.22757459  0.2761066   0.56519628  0.70383507]
 [ 0.10005569  0.31175494  0.93085307  0.05551481]]


In [14]:
a = np.array([[2,3],[4,5]])
b = torch.from_numpy(a)
print(b)

tensor([[ 2,  3],
        [ 4,  5]], dtype=torch.int32)


运算和 numpy 类似

In [15]:
x = torch.rand(5,4)
y = torch.rand(5,4)
c = 3

In [17]:
print(c * x)

tensor([[ 1.4698,  0.5713,  0.5707,  1.9875],
        [ 2.8717,  2.4169,  2.7111,  1.7490],
        [ 2.0731,  2.4739,  0.8732,  2.8371],
        [ 2.7190,  2.2233,  2.7300,  2.9132],
        [ 2.6850,  0.0662,  1.7391,  1.9291]])


In [18]:
print(x + y)

tensor([[ 0.5905,  0.5386,  0.3262,  0.7107],
        [ 1.2793,  1.1548,  1.1620,  0.9617],
        [ 0.6923,  1.3231,  0.7628,  1.8557],
        [ 1.5553,  1.6721,  1.4354,  1.1975],
        [ 1.0541,  0.9008,  1.0414,  0.7672]])


In [19]:
print(x.add(y))

tensor([[ 0.5905,  0.5386,  0.3262,  0.7107],
        [ 1.2793,  1.1548,  1.1620,  0.9617],
        [ 0.6923,  1.3231,  0.7628,  1.8557],
        [ 1.5553,  1.6721,  1.4354,  1.1975],
        [ 1.0541,  0.9008,  1.0414,  0.7672]])


In [21]:
# 可以直接进行操作改变原对象，x+y 或者 x.add() 并不会改变x，但是 x.add_() 则会对 x 进行改变
x.add_(y)

tensor([[ 0.6910,  0.8867,  0.4621,  0.7589],
        [ 1.6014,  1.5041,  1.4204,  1.3404],
        [ 0.6936,  1.8216,  1.2345,  2.7658],
        [ 2.2043,  2.6030,  1.9609,  1.4240],
        [ 1.2132,  1.7794,  1.5032,  0.8913]])

In [22]:
print(x)

tensor([[ 0.6910,  0.8867,  0.4621,  0.7589],
        [ 1.6014,  1.5041,  1.4204,  1.3404],
        [ 0.6936,  1.8216,  1.2345,  2.7658],
        [ 2.2043,  2.6030,  1.9609,  1.4240],
        [ 1.2132,  1.7794,  1.5032,  0.8913]])


将 torch.Tensor 放到 GPU 上

In [24]:
# 判断一下电脑是否支持 GPU
torch.cuda.is_available()

False

### 1.2、torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是 torch.autograd.Variable  
本质上 Variable 和 Tensor 没有什么区别，不过 Variable 会放在一个计算图里面，可以进行前向传播和反向传播以及求导  
里面的 creator 表示通过什么操作得到的这个 Variable ，grad 表示反向传播的梯度  

In [25]:
from torch.autograd import Variable

In [26]:
# requires_grad 表示是否对其求梯度，默认是 False
x = Variable(torch.Tensor([3]),requires_grad=True)
y = Variable(torch.Tensor([5]),requires_grad=True)
z = 2 * x + y + 4

In [27]:
# 对 x 和 y 分别求导
z.backward()

In [29]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([ 2.])
dz/dy: tensor([ 1.])


### 1.3、神经网络部分
所依赖的主要是 torch.nn 和 torch.nn.functional  
torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次  
torch.nn.functional 表示的是直接对其做一次向前运算操作

In [30]:
from torch import nn
import torch.nn.functional as F

In [31]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10 ,3)
        # 具体每种层的参数可以去查看文档
    def forward(self, x):
        # 定义前向传播
        out = self.conv1(x)
        return out